# Generated by Django 5.1.6 on 2025-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pagina', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coincidencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_url', models.TextField(blank=True, null=True)),
                ('usuario_url', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coincidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_url', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario_url', models.TextField(blank=True, null=True)),
                ('nombre_pagina', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
    ]
